### В этом Notebook:

Мы попрактикуемся решать разные задачи и закрепим пройденные знания по всему блоку.

### Задача 1
Создайте словарь из строки 'AnyOnebank' следующим образом: в качестве ключей возьмите буквы строки, а значениями пусть будут числа, соответствующие количеству вхождений дан|ной буквы в строку.

In [1]:
str1 = 'AnyOnebank'
# Напишите свое решение здесь

### Задача 2
У нас есть список, содержащий информацию о среднедневной температуре в Фаренгейтах за произвольный период по странам (структура данных в примере). Необходимо написать код, который рассчитает среднюю температуру за период в Цельсиях для каждой страны.

In [41]:
countries_temperature = [
    ['Thailand', [75.2, 77, 78.8, 73.4, 68, 75.2, 77]],
    ['Germany', [57.2, 55.4, 59, 59, 53.6]],
    ['Russia', [35.6, 37.4, 39.2, 41, 42.8, 39.2, 35.6]],
    ['Poland', [50, 50, 53.6, 57.2, 55.4, 55.4]]]
# Напишите свое решение здесь:

Результат: \
Средняя температура в странах:
- Thailand  -  23.9 С
- Germany  -  13.8 С
- Russia  -  3.7 С
- Poland  -  12.0 С

### Задача 3
1. Напишите функцию с названием multiply_by_three, которая принимает на вход в качестве параметра положительные числа (включая 0).
2. В случае если число положительное, то это число необходимо умножить на 3. 
3. В случае если число равно 0, то возвращаем 0.

In [24]:
# Решение должно быть здесь

In [23]:
# Для проверки вашего решения выполните данную ячейку, если ячейка завершилась без ошибок, значит вы решили
# все правильно, иначе будет ошибка
def test_task_1(): 
    assert multiply_by_three(5) == 15
    assert multiply_by_three(0) == 0 
    assert multiply_by_three(-4) == 0 

test_task_1()

### Задача 4
У вас есть два списка **а** и **b**, в котором представлены разные языки программирования. 
Ваша задача:
1. Посчитать сколько раз встретилось значение "Python" в обоих списках.
2. После всех подсчетов необходимо запомнить результат в переменную **cheeky**

In [ ]:
a = ['Python', 'R', 'SQL','Python', 'Git', 'Tableau', 'SAS', 'Python']
b = ['Python', 'R', 'SQL', 'Python', 'Git', 'Tableau', 'SAS', 'Python', 'Python']

# Напишите свое решение ниже

Ответом вашего решения должна быть цифра 7.

### Задача 5
Напишите функцию backward_string с 1 одним входным параметром типа str, которая вернет строки в перевернутом виде.

Для проверки использовать данные примеры
- "val" == "lav"
- "ohho" == "ohho"
- "123456789" == "987654321"
- " " == " "

In [42]:
# Напишите свое решение ниже

### Задача 6
Напишите функцию is_all_upper, которая принимает 1 параметр типа str. Проверьте все ли символы в строке являются заглавными. Если строка пустая или в ней нет букв - функция должна вернуть True.

Для проверки можно использовать следующие примеры:
- "ALL UPPER" == True
- "all lower" == False
- "444" == False
- " " == True

In [ ]:
# Напишите свое решение ниже

### Задача 7

Напишите скрипт, который имитирует работу банкомата. Скрипт должен состоять из 4 функций.
1. Напишите функцию rename_account_name, которая будет в диалоговом окне Python спрашивать вас **Ввести новое название счета**. Данная функция не принимает никаких входных параметров, на выходе возвращает новое название счета. 
2. Напишите функцию add_money, которая принимает целочисленный параметр balance и в теле фунцкии будет спрашивать **Какую сумму хотите внести на карту?**. На выходе функция возвращает результат суммирования баланса до внесения + внесенной суммы. 
3. Напишите функцию withdraw, которая принимает целочисленный параметр balance и в теле фунцкии будет спрашивать **"Какую сумму хотите снять с карты?"**. На выходе функция возвращает результат вычета баланса до снятия - сумму введенную вами для снятия. 
4. Создайте функцию enter_card, которая принимает 3 входных параметра:
- account_name типа str
- currency типа str
- balance типа int, должна принимать значение 0 по умолчанию 

В теле функции enter_card должно быть реализовано следующее:
1. Функция должна распечатывать текущее название счета, валюту и баланс
    - В формате: Добро пожаловать! Ваш счет: account_name, Валюта счета: currency, Баланс на счете: balance"
2. Необходимо переименовать название счета на **RBRU** с помощью функции rename_account_name
3. Необходимо к текущему balance внести наличные в размере 100 рублей, используя функцию add_money
4. Снять с текущего balance 50 рублей, используя функцию withdraw
5. На выходе функция должна распечатывать название счета, валюту счета, баланс на счете.
     - В формате: До скорых встреч! Ваш счет: account_name, Валюта счета: currency, Баланс на счете: balance"

In [ ]:
# Если вы что-то не помните или не знаете не стесняйтесь искать информацию в Интернете
# Напишите свое решение здесь 

# В качестве входных параметров функции enter_card использовать: 
enter_card("RBI", "RUBLES")

В качестве ответа вы должны получить: \
**До скорых встреч! Ваш счет: RBRU, Валюта счета: RUBLES, Баланс на счете: 50**

### Задача 8
Дан словарь с числовыми значениями. Необходимо их все перемножить и вывести на экран.

In [43]:
my_dictionary = {'data1': 375, 'data2': 567, 'data3': -37, 'data4': 21}
# Напишите свое решение здесь

В качестве ответа должно получится -165209625

### Задача 9 

Дан массив целых чисел. Нужно найти сумму элементов с четными индексами (0-й, 2-й, 4-й итд), затем перемножить эту сумму и последний элемент исходного массива. Не забудьте, что первый элемент массива имеет индекс 0.

Для пустого массива результат всегда 0 (ноль).

Входные данные: Список (list) целых чисел (int).

Выходные данные: Число как целочисленное (int).

Примеры для проверки:
- [0, 1, 2, 3, 4, 5] == 30 
- [1, 3, 5] == 30 
- [6] == 36 
- [] == 0

In [45]:
# Напишите свое решение здесь